name: Build Web Application

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: ${{ github.run_number }}
  VERSION: 1.0.0
  PYTHON_VERSION: '3.9'
  FLUTTER_VERSION: '2.5.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable
          echo "${{ github.workspace }}/flutter/bin" >> $GITHUB_PATH

      - name: Build the web application
        run: |
          flutter pub get
          flutter build web

      - name: Verify build output
        run: |
          if [ ! -d "build/web" ]; then
            echo "Build failed!"
            exit 1
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: web-build
          path: build/web