name: Flutter Web Build

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.12.2
  FLUTTER_VERSION: 3.22.2

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || echo "No requirements.txt found, skipping..."

    - name: Setup Flutter ${{ env.FLUTTER_VERSION }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Verify Flutter Project Root
      run: ls -la
      working-directory: myapp  # Ensure the folder exists

    - name: Install Flutter Dependencies
      working-directory: myapp
      run: flutter pub get

    - name: Build Flutter Web
      working-directory: myapp
      run: |
        flutter config --no-analytics
        flutter build web --release --base-href=/ --build-number=$BUILD_NUMBER

    - name: Upload Web Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: web-build-artifact
        path: myapp/build/web  # Corrected path
        if-no-files-found: warn
        overwrite: false
